version: "3.8"
services:
  mysqldb :
    image: "mysql"
    volumes:
      - data:/data/db
    ports:
      - "3306:3306"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "database_name"
      MYSQL_USER: "mysql"
      MYSQL_PASSWORD: "root"
  backend:
    build: ./backend
    ports:
      - "3001:3001"
    volumes:
      - ./backend:/app
      - /app/node_modules

    depends_on:
      - mysqldb
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
       - ./frontend/src:/app1/src
    stdin_open: true
    tty: true
    depends_on:
      - backend

volumes:
  data: